export default [
    { id: 1, name: "Apple", amount: "100 g" },
    { id: 2, name: "Banana", amount: "1 pc" },
    { id: 3, name: "Orange", amount: "2 pcs" },
    { id: 4, name: "Strawberries", amount: "250 g" },
    { id: 5, name: "Blueberries", amount: "150 g" },
    { id: 6, name: "Spinach", amount: "200 g" },
    { id: 7, name: "Broccoli", amount: "300 g" },
    { id: 8, name: "Carrot", amount: "2 pcs" },
    { id: 9, name: "Tomato", amount: "3 pcs" },
    { id: 10, name: "Cucumber", amount: "1 pc" },
    { id: 11, name: "Avocado", amount: "1 pc" },
    { id: 12, name: "Potato", amount: "500 g" },
    { id: 13, name: "Onion", amount: "2 pcs" },
    { id: 14, name: "Garlic", amount: "3 cloves" },
    { id: 15, name: "Milk", amount: "1 L" },
    { id: 16, name: "Yogurt", amount: "200 g" },
    { id: 17, name: "Eggs", amount: "12 pcs" },
    { id: 18, name: "Chicken", amount: "500 g" },
    { id: 19, name: "Rice", amount: "1 kg" },
    { id: 20, name: "Pasta", amount: "500 g" }
];
